# Generated by Django 6.0.1 on 2026-01-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('is_all_items', models.BooleanField(default=False)),
                ('reference', models.CharField(choices=[('high', 'High Price'), ('low', 'Low Price')], max_length=4)),
                ('is_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
