# Generated by Django 6.0.1 on 2026-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='type',
        ),
        migrations.AddField(
            model_name='alert',
            name='above_below',
            field=models.CharField(blank=True, choices=[('above', 'Above'), ('below', 'Below')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='direction',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_all_items',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_triggered',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='item_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='item_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='reference',
            field=models.CharField(blank=True, choices=[('high', 'High Price'), ('low', 'Low Price')], default=None, max_length=4, null=True),
        ),
    ]
