# Generated by Django 6.0.1 on 2026-01-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_remove_alert_type_alert_above_below_alert_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold')], max_length=10, null=True),
        ),
    ]
