# Generated by Django 6.0.1 on 2026-01-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_alert_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_active',
        ),
    ]
