# Generated by Django 6.0.1 on 2026-01-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_remove_alert_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_triggered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold')], default='above', max_length=10, null=True),
        ),
    ]
