# Generated by Django 6.0.1 on 2026-01-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alert_is_active_alter_alert_is_triggered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_all_items',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
