# Generated by Django 6.0.1 on 2026-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_alter_alert_is_all_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_dismissed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
