# Generated by Django 6.0.1 on 2026-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_alert_is_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold'), ('spread', 'Spread')], default='above', max_length=10, null=True),
        ),
    ]
