# Generated by Django 6.0.1 on 2026-01-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_alert_percentage_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='triggered_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
