# Generated by Django 6.0.1 on 2026-01-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_alert_triggered_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='maximum_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='minimum_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
