# Generated by Django 6.0.1 on 2026-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_alert_maximum_price_alert_minimum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
