# Generated by Django 6.0.1 on 2026-01-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_alert_email_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='Website.alertgroup'),
        ),
    ]
