# Generated by Django 6.0.1 on 2026-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alertgroup_alert_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='direction',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold'), ('spread', 'Spread'), ('spike', 'Spike')], default='above', max_length=10, null=True),
        ),
    ]
