# Generated by Django 6.0.1 on 2026-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_alter_alert_direction_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
