# Generated by Django 6.0.1 on 2026-01-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_alert_triggered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('average_cost', models.FloatField(default=0)),
                ('unrealized_net', models.FloatField(default=0)),
                ('realized_net', models.FloatField(default=0)),
                ('quantity_held', models.IntegerField(default=0)),
            ],
        ),
    ]
