# Generated by Django 6.0.1 on 2026-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_flipprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipprofit',
            name='item_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
