# Generated by Django 6.0.1 on 2026-01-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_flipprofit_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='min_consecutive_moves',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='min_move_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='min_volume',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='volatility_buffer_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='volatility_multiplier',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold'), ('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move')], default='above', max_length=10, null=True),
        ),
    ]
