# Generated by Django 6.0.1 on 2026-01-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_alert_min_consecutive_moves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sustained_item_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
