# Generated by Django 6.0.1 on 2026-01-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_alert_sustained_item_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='time_frame',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
