# Generated by Django 6.0.1 on 2026-01-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_add_time_frame_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='min_pressure_spread_pct',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='min_pressure_strength',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], default=None, max_length=10, null=True),
        ),
    ]
