# Generated by Django 6.0.1 on 2026-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0021_add_pressure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image_key',
            field=models.CharField(blank=True, default='auto', max_length=32),
        ),
    ]
