# Generated by Django 6.0.1 on 2026-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_add_alert_image_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='image_key',
            field=models.CharField(blank=True, default='auto', max_length=255),
        ),
    ]
