# Generated by Django 6.0.1 on 2026-01-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0023_alter_alert_image_key_len'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='image_key',
        ),
    ]
