# Generated by Django 6.0.1 on 2026-01-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_remove_alert_image_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-added_at'],
            },
        ),
    ]
