# Generated by Django 6.0.1 on 2026-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0028_favoritegroup_favoriteitem_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='group',
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='items', to='Website.favoritegroup'),
        ),
    ]
