# Generated by Django 6.0.1 on 2026-01-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0029_remove_favoriteitem_group_favoriteitem_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_name',
            field=models.CharField(default='Default', max_length=255),
        ),
    ]
