# Generated by Django 6.0.1 on 2026-01-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0030_add_alert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='item_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
