# Generated by Django 6.0.1 on 2026-01-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0031_alert_item_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='show_notification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
