# Generated by Django 6.0.1 on 2026-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0032_add_show_notification_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='threshold_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('value', 'Value')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='reference',
            field=models.CharField(blank=True, choices=[('high', 'High Price'), ('low', 'Low Price'), ('average', 'Average Price')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold'), ('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold')], default='above', max_length=10, null=True),
        ),
    ]
