# Generated by Django 6.0.1 on 2026-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0033_alert_threshold_type_alter_alert_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='reference_prices',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='target_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
