# Generated by Django 6.0.1 on 2026-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0034_alert_reference_prices_alert_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='baseline_method',
            field=models.CharField(blank=True, choices=[('single_point', 'Single Point'), ('average', 'Window Average'), ('min_max', 'Min/Max')], default='single_point', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='baseline_prices',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
