# Generated by Django 6.0.1 on 2026-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0035_alert_baseline_method_alert_baseline_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold')], default='threshold', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ItemPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True)),
                ('item_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('avg_high_price', models.IntegerField(blank=True, null=True)),
                ('avg_low_price', models.IntegerField(blank=True, null=True)),
                ('high_price_volume', models.BigIntegerField(default=0)),
                ('low_price_volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', 'item_name'],
                'indexes': [models.Index(fields=['item_id', '-timestamp'], name='Website_ite_item_id_25f766_idx'), models.Index(fields=['-timestamp'], name='Website_ite_timesta_532d4b_idx')],
                'unique_together': {('item_id', 'timestamp')},
            },
        ),
    ]
