# Generated by Django 6.0.1 on 2026-02-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0037_itemcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='calculation_method',
            field=models.CharField(blank=True, choices=[('simple', 'Non Weighted'), ('weighted', 'Weighted by Value')], default='simple', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold'), ('collective_move', 'Collective Move')], default='threshold', max_length=25, null=True),
        ),
    ]
