# Generated by Django 6.0.1 on 2026-02-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0038_alert_calculation_method_alter_alert_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='calculation_method',
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold')], default='threshold', max_length=10, null=True),
        ),
    ]
