# Generated by Django 6.0.1 on 2026-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0040_alert_calculation_method_alter_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyItemVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True)),
                ('item_name', models.CharField(max_length=255)),
                ('volume', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['item_id', '-timestamp'], name='Website_hou_item_id_e2e59d_idx')],
            },
        ),
    ]
