# Generated by Django 6.0.1 on 2026-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0041_create_hourly_item_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyitemvolume',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
