# Generated by Django 6.0.1 on 2026-02-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0042_alter_hourlyitemvolume_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hourlyitemvolume',
            name='Website_hou_item_id_e2e59d_idx',
        ),
    ]
