# Generated by Django 6.0.1 on 2026-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0043_remove_hourlyitemvolume_website_hou_item_id_e2e59d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confidence_cooldown',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_eval_interval',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_last_scores',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_lookback',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_min_spread_pct',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_min_volume',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_sustained_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_threshold',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_timestep',
            field=models.CharField(blank=True, choices=[('5m', '5 Minutes'), ('1h', '1 Hour'), ('6h', '6 Hours'), ('24h', '24 Hours')], default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_trigger_rule',
            field=models.CharField(blank=True, choices=[('crosses_above', 'Score Crosses Above Threshold'), ('delta_increase', 'Score Increases By Threshold')], default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_weight_pressure',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_weight_spread',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_weight_stability',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_weight_trend',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_weight_volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold'), ('collective_move', 'Collective Move'), ('flip_confidence', 'Flip Confidence')], default='threshold', max_length=25, null=True),
        ),
    ]
