# Generated by Django 6.0.1 on 2026-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0044_alert_confidence_cooldown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveMinTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True)),
                ('item_name', models.CharField(max_length=255)),
                ('avg_high_price', models.IntegerField(blank=True, null=True)),
                ('avg_low_price', models.IntegerField(blank=True, null=True)),
                ('high_price_volume', models.IntegerField(default=0)),
                ('low_price_volume', models.IntegerField(default=0)),
                ('timestamp', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
