# Generated by Django 6.0.1 on 2026-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0045_fivemintimeseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='confidence_min_volume',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
