# Generated by Django 6.0.1 on 2026-02-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0049_twentyfourhourtimeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dump_confirmation_buckets',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_consistency_required',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_cooldown',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_discount_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_fair_halflife',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_liquidity_floor',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_rel_vol_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_sell_ratio_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_shock_sigma',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_state',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_var_halflife',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dump_vol_halflife',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold'), ('collective_move', 'Collective Move'), ('flip_confidence', 'Flip Confidence'), ('dump', 'Dump')], default='threshold', max_length=25, null=True),
        ),
    ]
