# Generated by Django 6.0.1 on 2026-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0050_add_dump_alert_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confidence_filter_outliers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence_filter_vol_concentration',
            field=models.BooleanField(default=False),
        ),
    ]
