# Generated by Django 6.0.1 on 2026-02-07 19:11

from django.db import migrations, models


def convert_vol_concentration_to_float(apps, schema_editor):
    Alert = apps.get_model('Website', 'Alert')
    old_field = Alert._meta.get_field('confidence_filter_vol_concentration')
    new_field = models.FloatField(blank=True, default=None, null=True)
    new_field.set_attributes_from_name('confidence_filter_vol_concentration')

    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            '''
            ALTER TABLE "Website_alert"
            ALTER COLUMN "confidence_filter_vol_concentration" DROP DEFAULT,
            ALTER COLUMN "confidence_filter_vol_concentration" TYPE double precision
                USING CASE
                    WHEN "confidence_filter_vol_concentration" THEN 100.0
                    ELSE NULL
                END,
            ALTER COLUMN "confidence_filter_vol_concentration" DROP NOT NULL
            '''
        )
    else:
        schema_editor.alter_field(Alert, old_field, new_field)


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0051_add_confidence_filter_vol_concentration_and_outliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='confidence_filter_outliers',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    convert_vol_concentration_to_float,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='alert',
                    name='confidence_filter_vol_concentration',
                    field=models.FloatField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
