# Generated by Django 6.0.1 on 2026-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0052_change_vol_concentration_to_float_remove_outliers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fivemintimeseries',
            index=models.Index(fields=['item_id', '-timestamp'], name='five_min_item_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='fivemintimeseries',
            index=models.Index(fields=['timestamp'], name='five_min_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyitemvolume',
            index=models.Index(fields=['item_id', '-timestamp'], name='hourly_vol_item_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='hourlyitemvolume',
            index=models.Index(fields=['timestamp'], name='hourly_vol_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='onehourtimeseries',
            index=models.Index(fields=['item_id', '-timestamp'], name='one_hour_item_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='onehourtimeseries',
            index=models.Index(fields=['timestamp'], name='one_hour_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='sixhourtimeseries',
            index=models.Index(fields=['item_id', '-timestamp'], name='six_hour_item_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='sixhourtimeseries',
            index=models.Index(fields=['timestamp'], name='six_hour_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='twentyfourhourtimeseries',
            index=models.Index(fields=['item_id', '-timestamp'], name='twentyfour_item_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='twentyfourhourtimeseries',
            index=models.Index(fields=['timestamp'], name='twentyfour_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='fivemintimeseries',
            constraint=models.UniqueConstraint(fields=('item_id', 'timestamp'), name='uniq_5m_item_ts'),
        ),
        migrations.AddConstraint(
            model_name='hourlyitemvolume',
            constraint=models.UniqueConstraint(fields=('item_id', 'timestamp'), name='uniq_hourly_vol_item_ts'),
        ),
        migrations.AddConstraint(
            model_name='onehourtimeseries',
            constraint=models.UniqueConstraint(fields=('item_id', 'timestamp'), name='uniq_1h_item_ts'),
        ),
        migrations.AddConstraint(
            model_name='sixhourtimeseries',
            constraint=models.UniqueConstraint(fields=('item_id', 'timestamp'), name='uniq_6h_item_ts'),
        ),
        migrations.AddConstraint(
            model_name='twentyfourhourtimeseries',
            constraint=models.UniqueConstraint(fields=('item_id', 'timestamp'), name='uniq_24h_item_ts'),
        ),
    ]
