# Generated by Django 6.0.1 on 2026-04-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0053_add_timeseries_indexes_and_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFeedbackWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True)),
                ('item_name', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('target_price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('sms_notification', models.BooleanField(default=False)),
                ('sms_recipient', models.EmailField(blank=True, default='', max_length=254)),
                ('last_checked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_market_price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('last_market_time', models.BigIntegerField(blank=True, default=None, null=True)),
                ('last_status', models.CharField(choices=[('watching', 'Watching'), ('undercut', 'Undercut'), ('overcut', 'Overcut'), ('no_price', 'No recent price'), ('paused', 'Paused')], default='watching', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_feedback_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_triggered', '-is_active', 'item_name', 'target_price'],
                'indexes': [
                    models.Index(fields=['user', 'is_active'], name='livefb_user_active_idx'),
                    models.Index(fields=['is_active', 'is_triggered'], name='livefb_active_trig_idx'),
                    models.Index(fields=['item_id', 'side'], name='livefb_item_side_idx'),
                    models.Index(fields=['last_status'], name='livefb_status_idx'),
                ],
            },
        ),
    ]
