# Generated by Django 6.0.1 on 2026-04-29 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0055_flipjournal_flipjournalexit_flipjournalnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('spread', 'Spread'), ('spike', 'Spike'), ('sustained', 'Sustained Move'), ('threshold', 'Threshold'), ('collective_move', 'Collective Move'), ('flip_confidence', 'Flip Confidence'), ('dump', 'Dump')], db_index=True, default='threshold', max_length=25, null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active', 'type'], name='alert_active_type_idx'),
        ),
    ]
