# Generated by Django 6.0.1 on 2026-05-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0059_alltimedata_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_items', models.JSONField(blank=True, default=list)),
                ('threshold_kind', models.CharField(choices=[('percent_profit', '% Profit'), ('percent_loss', '% Loss'), ('gp_profit', 'GP Profit'), ('gp_loss', 'GP Loss')], max_length=20)),
                ('threshold_value', models.FloatField()),
                ('email_notification', models.BooleanField(default=False)),
                ('sms_notification', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_triggered', models.BooleanField(db_index=True, default=False)),
                ('active_item_ids', models.JSONField(blank=True, default=list)),
                ('triggered_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flip_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='flip_alert_user_active_idx')],
            },
        ),
    ]
